### ISSUE TITLE
ONNX Backend test crashes

### ISSUE THREAD

**Issue by attila-dusnoki-htec** [migraphx-benchmark/AMDMIGraphX#180]
The following tests are crashing:
- [ ] test_resize_downsample_scales_nearest_cpu
- [ ] test_resize_upsample_scales_nearest_cpu
- [ ] test_resize_upsample_sizes_nearest_cpu
- [ ] test_resize_downsample_sizes_nearest
- [ ] test_resize_upsample_sizes_nearest_floor_align_corners_cpu
- [ ] test_resize_upsample_sizes_nearest_round_prefer_ceil_asymmetric_cpu
- [ ] test_resize_upsample_sizes_nearest_ceil_half_pixel_cpu
- [ ] test_unique_not_sorted_without_axis_cpu
- [ ] test_unique_sorted_with_axis_cpu
- [ ] test_unique_sorted_without_axis_cpu

**Comment by nives-vukovic** [comment]
**Unique** operator test crashes listed in the issue occur due to output being a dynamic shape.

Two remaining backend tests _test_unique_sorted_with_negative_axis_cpu_ and _test_unique_sorted_with_axis_3d_cpu_ currently return an error because the operator only supports axis = 0 or None. They would also return a dynamic shape and crash if all axis values are supported.

**Comment by nives-vukovic** [comment]
**Resize** operator test crashes listed in the issue occur due to output being a dynamic shape.

Remaining tests currently return an error because some attribute values are not supported. They would also return a dynamic shape and crash if those features are supported. There are some cases when operator can return a non-dynamic shape, but it seems python backend tests all have a dynamic shape output.
