### ISSUE TITLE
ONNX Backend test fails

### ISSUE THREAD

**Issue by attila-dusnoki-htec** [migraphx-benchmark/AMDMIGraphX#181]
The following test fails with `allocate_gpu: Memory not available to allocate buffer: 18446744073709551397`

- [ ] test_constantofshape_float_ones_cpu
- [ ] test_constantofshape_int_shape_zero_cpu
- [ ] test_constantofshape_int_zeros_cpu
- [ ] test_slice_default_axes_cpu
- [ ] test_slice_default_steps_cpu
- [ ] test_slice_negative_axes_cpu

**Comment by nives-vukovic** [comment]
**ConstantOfShape** operator test fails listed in the issue occur due to output being a dynamic shape.

**Slice** operator test fails listed in the issue occur due to output being a dynamic shape.

Remaining slice tests currently return an error because slice cannot handle variable steps. They would also return a dynamic shape and fail if this is supported.
